name: 'URLWatch Website Change Detector'
description: 'Monitor web pages for changes using urlwatch with GitHub Actions'
branding:
  icon: eye
  color: blue
inputs:
  urls:
    description: 'Content of the urls.yaml file for urlwatch'
    required: true
  settings:
    description: 'Content of the urlwatch.yaml file for urlwatch'
    required: false
    default: |
      display:
        empty-diff: true
        error: true
        new: true
        unchanged: false
      job_defaults:
        all:
          treate_new_as_changed: true
        browser: {}
        shell: {}
        url: {}
      report:
        stdout:
          color: false
          enabled: true
        text:
          details: true
          footer: false
          line_length: 120
          minimal: false
          separate: false
  hooks:
    description: 'Content of the hooks.py file for urlwatch'
    required: false
  cache-name:
    description: 'Name for the cache persistence artifact'
    required: false
    default: 'urlwatch-cache'
  token:
    description: 'A github token'
    required: true
outputs:
  changes:
    value: ${{ steps.urlwatch-exec.outputs.changes }}
    description: 'Raw output of detected changes from urlwatch'
  report:
    value: ${{ steps.urlwatch-exec.outputs.report }}
    description: 'Formatted markdown report of changes'
runs:
  using: 'composite'
  steps:
    - name: Install urlwatch
      run: pip install urlwatch jq
      shell: bash

    - name: Configure urlwatch
      run: |
        mkdir -p ~/.config/urlwatch ~/.cache/urlwatch
        # cp -r "${{ inputs.config-dir }}"/* ~/.config/urlwatch/
        cat <<EOF > ~/.config/urlwatch/urls.yaml
        ${{ inputs.urls }}
        EOF
        cat <<EOF > ~/.config/urlwatch/urlwatch.yaml
        ${{ inputs.settings }}
        EOF
        if [[ -n "${{ inputs.hooks }}" ]]; then
        cat <<EOF > ~/.config/urlwatch/hooks.py
        ${{ inputs.hooks }}
        EOF
        fi
      shell: bash

    - name: Find previous cache
      id: last-run
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      continue-on-error: true
      with:
        script: |
          const path = require('path');

          const workflowRef = process.env.GITHUB_WORKFLOW_REF;
          const filePath = workflowRef.split('@')[0];
          const workflow_id = path.basename(filePath);

          // Fetch the most recent successful workflow run for this workflow file
          const response = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id,
            status: 'success',
            per_page: 1
          });

          // Set the output to the run ID, or 0 if not found
          core.setOutput('run_id', response.data.workflow_runs[0]?.id || 0);

    - name: Restore urlwatch cache
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      continue-on-error: true
      with:
        name: ${{ inputs.cache-name }}
        github-token: ${{ inputs.token }}
        run-id: ${{ steps.last-run.outputs.run_id }}
      if: ${{ steps.last-run.outputs.run_id != 0 }}

    - name: Execute monitoring
      id: urlwatch-exec
      run: |
        # Move downloaded cache if exists
        if [[ -f cache.db ]]; then
          mv cache.db ~/.cache/urlwatch/
        fi
        
        output=$(urlwatch)
        echo "changes<<EOF" >> $GITHUB_OUTPUT
        echo "$output" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        echo "report<<EOF" >> $GITHUB_OUTPUT
        echo "\`\`\`" >> $GITHUB_OUTPUT
        echo "$output" >> $GITHUB_OUTPUT
        echo "\`\`\`" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Preserve new cache state
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: ${{ inputs.cache-name }}
        path: ~/.cache/urlwatch/cache.db
